title: Like A Cloud
logo_img: /Users/likeacloud/Desktop/blog/likeacloud.github.io/assets/img/icons/IMG_4060.jpg
favicon: /assets/favicon.ico
description: description
global_tags: jekyll theme simplex golasblog responsive html5
copyright: © LikeACloud 2024

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"